[tool.poetry]
name = "netswitcher"
version = "0.1.0"
description = ""
authors = ["Fearkin <aloneWorker@yandex.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.6"
typer = "^0.9.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
